### ISSUE TITLE
Make A PocketMine Phar Zip To Phar

### ISSUE THREAD

**Issue by ExplodingCraftPE** [pmt-mcpe-fun/pmt.mcpe.fun#13]
Hi Im A Dev
I Use Devtools But Its Preety Hard
I Found pmt.mcpe.me i make some phars there but the day
pmt.mcpe.me gone i cannot make pocketmine-mp phars pls add 
pmmp phar maker

**Comment by Ad5001** [comment]
Hello.
Have you ever heard about "running from src"? Well that's a technik allowing you to run PocketMine from the src form, not phar packaged. For this, put src folder of the phar you want to run in your server root folder then start your server!

**Comment by NFGamerMC** [comment]
[PMT](https://pmt.mcpe.fun) is meant for compiling plugins not [PocketMine-MP](https://github.com/pmmp/PocketMine-MP), to compile software you must run from src as @Ad5001 said then with the DevTools plugin from [Poggit](https://poggit.pmmp.io), run `makeserver` then that will compile to code into a .phar. Then do the following command from the directory that PocketMine is installed in `mv plugins/DevTools/Pocket* /../../../` You can also get the latest PocketMine build from [Jenkins](https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/) or [Poggit](https://poggit.pmmp.io/ci/pmmp/PocketMine-MP/PocketMine-MP)

**Comment by NFGamerMC** [comment]
`Just FYI if you cannot use DevTools you cannot code Plugins.`

**Comment by ExplodingCraftPE** [comment]
put like the old pmp.mcpe.me

**Comment by ExplodingCraftPE** [comment]
i cannot use devtools

**Comment by ExplodingCraftPE** [comment]
harrddddd

**Comment by Ad5001** [comment]
The problem is that pmt.mcpe.fun is a web tool for not codish people. You cannot create a spoon if you dont know how to use devtools. If you need to compile a spoon on the internet, they may provide a phar, or you'll be running from src directly.
This feature is here to prevent crappy spoon made  by people that don't know how to code.

**Comment by NFGamerMC** [comment]
@ExplodingCraftPE Your account is less than a month old and you have two forks of spoons. If you cannot use DevTools you cannot be a Developer of any type as DevTools requires at least basic skill with the **Command Line Interface**. This issue will be locked and another response you will be banned from creating issues. Good Luck!

**Comment by NFGamerMC** [comment]
We will not change our design due two one person. You can create a petition on **change.org** and I may choose to mix it up a bit.
